workflows:
  android-workflow:
    name: Jarvis Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      java: 11

    cache:
      cache_paths: []   

    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
      - name: Build release AAB
        script: flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      email:
        recipients:
          - bhanuforprime12039@gmail.com  
